# Generated by Django 5.2.16 on 2026-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transformation_type',
            field=models.CharField(choices=[('FIND_REPLACE', 'Find and Replace'), ('EXTRACT', 'Extract to New Column'), ('STANDARDIZE_FORMAT', 'Standardize Format')], default='FIND_REPLACE', max_length=30),
        ),
    ]
